### ISSUE TITLE
jsxhint 0.13.0 crashes

### ISSUE THREAD

**Issue by danvk** [STRML/JSXHint#58]
I just updated to jsxhint 0.13.0 and am getting this error whenever I run it:

```
$ ./node_modules/.bin/jsxhint --harmony src/utils.js

/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:36
        fn = function () { throw arg; };
                                 ^
TypeError: Cannot read property 'line' of undefined
    at /Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/jshint/src/reporters/default.js:20:39
    at Array.forEach (native)
    at module.exports.reporter (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/jshint/src/reporters/default.js:11:13)
    at Object.reporter (/Users/danvk/github/pileup.js/node_modules/jsxhint/cli.js:135:12)
    at /Users/danvk/github/pileup.js/node_modules/jsxhint/cli.js:171:16
    at tryCatcher (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/util.js:24:31)
    at Promise.errorAdapter (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/nodeify.js:35:34)
    at Promise._settlePromiseAt (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/promise.js:528:21)
    at Promise._settlePromises (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:419:13)
```

Here's the source for that file, though it seems to happen universally: [`src/utils.js`][1].

[1]: https://github.com/hammerlab/pileup.js/blob/e079aaa99cf905914682834deec115d182477284/src/utils.js

**Comment by STRML** [comment]
Thanks. Will investigate now.

**Comment by STRML** [comment]
Please try `0.13.1`.

**Comment by danvk** [comment]
Now I get this error:

```
$ ./node_modules/.bin/jsxhint --harmony src/utils.js
Runtime error: SyntaxError: Unexpected token /
    at Object.parse (native)
    at Object.me.readFileSync (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/fs-extra/node_modules/jsonfile/lib/jsonfile.js:31:17)
    at copyConfig (/Users/danvk/github/pileup.js/node_modules/jsxhint/utils.js:107:27)
    at Object.copyConfig (/Users/danvk/github/pileup.js/node_modules/jsxhint/utils.js:118:14)
    at Object.createTempFile (/Users/danvk/github/pileup.js/node_modules/jsxhint/utils.js:139:11)
    at /Users/danvk/github/pileup.js/node_modules/jsxhint/utils.js:153:20
    at Array.map (native)
    at Object.createTempFiles (/Users/danvk/github/pileup.js/node_modules/jsxhint/utils.js:152:22)
    at /Users/danvk/github/pileup.js/node_modules/jsxhint/jsxhint.js:104:31
    at tryCatcher (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/danvk/github/pileup.js/node_modules/jsxhint/node_modules/bluebird/js/main/async.js:14:14)
```

**Comment by STRML** [comment]
Looks like a problem in your jshintrc, I'll have it throw a better error.
It tries to parse it as JSON. Can you check it?

**Comment by STRML** [comment]
Ah I see the issue you were having - .jshintrc is JSON but internally jshint uses `strip-json-comments` so you can write comments inside it. I'm now piggybacking on jshint.cli.loadConfig() so we can benefit from that as well. You should be good with `v0.13.2`.

**Comment by danvk** [comment]
Beautiful, thanks!
